{
 "title": "Rated Ethereum Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Monitored Keys",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rated_sentinel_monitored_keys)",
     "legendFormat": "Number of keys monitored"
    }
   ]
  },
  {
   "title": "1d Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rated_sentinel_validation_key_uptime) * 100.0",
     "legendFormat": "Current Uptime"
    }
   ]
  },
  {
   "title": "1d Block Proposals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rated_sentinel_validation_key_proposer_effectiveness)",
     "legendFormat": "Current Uptime"
    }
   ]
  },
  {
   "title": "1d Attestation Effectiveness",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rated_sentinel_validation_key_attester_effectiveness)",
     "legendFormat": "Current Uptime"
    }
   ]
  },
  {
   "title": "Validation Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(rated_sentinel_validation_key_uptime) * 100.0",
     "legendFormat": "Validation Uptime"
    }
   ]
  },
  {
   "title": "Proposal Effectiveness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "avg(rated_sentinel_validation_key_proposer_effectiveness)",
     "legendFormat": "Proposer Effectiveness"
    }
   ]
  },
  {
   "title": "Attestation Effectiveness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "avg(rated_sentinel_validation_key_attester_effectiveness)",
     "legendFormat": "Attestation Effectiveness"
    }
   ]
  }
 ]
}